### ISSUE TITLE
overcomplication in solve_coefficients

### ISSUE THREAD

**Issue by RileyPaddock** [C0BBL3/machine-learning#11]
In solve_coefficients you use a short apply coeffs method to set self.coefficents. This is a short function and you could put it at the end of solve_coefficients instead of having a whole other function and also you could just set self.coefficients = self.solve_coefficienst() in you __init__ function too.

**Comment by C0BBL3** [comment]
I created the function apply coeffs because in logistic regression and linear regressor the final coeffs are calculated differently, so instead of writing a new solve_coefficients() function I wrote a small apply_coeffs function which applies the logistic part of the logistic regression or the linear part of the linear regressor.

**Comment by C0BBL3** [comment]
fine i fixed it
